/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.1 		*/
/*  Created On : 07-cze-2024 12:46:43 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `Akt` CASCADE
;

DROP TABLE IF EXISTS `Grob` CASCADE
;

DROP TABLE IF EXISTS `Opiekungrobu` CASCADE
;

DROP TABLE IF EXISTS `Oplaceniemiejsca` CASCADE
;

DROP TABLE IF EXISTS `Osobauprawniona` CASCADE
;

DROP TABLE IF EXISTS `Osobazmarla` CASCADE
;

DROP TABLE IF EXISTS `Pozycjazamowienia` CASCADE
;

DROP TABLE IF EXISTS `Sprzataniegrobu` CASCADE
;

DROP TABLE IF EXISTS `Usluga` CASCADE
;

DROP TABLE IF EXISTS `UslugaPozycjaZamowienia` CASCADE
;

DROP TABLE IF EXISTS `Uzytkownik` CASCADE
;

DROP TABLE IF EXISTS `Zamowienie` CASCADE
;

DROP TABLE IF EXISTS `Zapalenieznicza` CASCADE
;

DROP TABLE IF EXISTS `Zarzadcagrobu` CASCADE
;

DROP TABLE IF EXISTS `Zastrzezenia` CASCADE
;

/* Create Tables */

CREATE TABLE `Akt`
(
	`Datarejestracjizgonu` DATE NULL,
	`Datawydania` DATE NULL,
	`Nazwaurzedu` VARCHAR(50) NULL,
	`Numer` INT NULL,
	`Oznaczenie` VARCHAR(50) NULL,
	`AktID` INT NOT NULL,
	`OsobazmarlaID` INT NULL,
	CONSTRAINT `PK_Akt` PRIMARY KEY (`AktID` ASC)
)

;

CREATE TABLE `Grob`
(
	`Kwatera` VARCHAR(50) NULL,
	`Numerwrzedzie` INT NULL,
	`Rodzajgrobu` VARCHAR(50) NULL,
	`Rzad` INT NULL,
	`Zabytek` BOOL NULL,
	`GrobID` INT NOT NULL,
	CONSTRAINT `PK_Grob` PRIMARY KEY (`GrobID` ASC)
)

;

CREATE TABLE `Opiekungrobu`
(
	`Datazapisania` DATE NULL,
	`Opis` VARCHAR(50) NULL,
	`OpiekungrobuID` INT NOT NULL,
	`GrobID` INT NULL,
	`UzytkownikID` INT NULL,
	CONSTRAINT `PK_Opiekungrobu` PRIMARY KEY (`OpiekungrobuID` ASC)
)

;

CREATE TABLE `Oplaceniemiejsca`
(
	`Okresoplaty` DATE NULL,
	`OplaceniemiejscaID` INT NOT NULL,
	CONSTRAINT `PK_Oplaceniemiejsca` PRIMARY KEY (`OplaceniemiejscaID` ASC)
)

;

CREATE TABLE `Osobauprawniona`
(
	`Imie` VARCHAR(50) NULL,
	`Nazwisko` VARCHAR(50) NULL,
	`Oznaczenieorganu` VARCHAR(50) NULL,
	`OsobauprawnionaID` INT NOT NULL,
	CONSTRAINT `PK_Osobauprawniona` PRIMARY KEY (`OsobauprawnionaID` ASC)
)

;

CREATE TABLE `Osobazmarla`
(
	`Chorobazakazna` BOOL NULL,
	`Danematki` VARCHAR(50) NULL,
	`Daneojca` VARCHAR(50) NULL,
	`Datanarodzin` DATE NULL,
	`Datapochowania` DATE NULL,
	`Datazgonu` DATE NULL,
	`Ekshumacja` BOOL NULL,
	`Imie` VARCHAR(50) NULL,
	`Miejscenarodzin` INT NULL,
	`Nazwisko` VARCHAR(50) NULL,
	`Opis` VARCHAR(50) NULL,
	`Pesel` INT NULL,
	`OsobazmarlaID` INT NOT NULL,
	`GrobID` INT NULL,
	CONSTRAINT `PK_Osobazmarla` PRIMARY KEY (`OsobazmarlaID` ASC)
)

;

CREATE TABLE `Pozycjazamowienia`
(
	`Potwierdzeniewykonania` VARCHAR(50) NULL,
	`Status` INT NULL,
	`PozycjazamowieniaID` INT NOT NULL,
	`GrobID` INT NOT NULL,
	`ZamowienieID` INT NOT NULL,
	CONSTRAINT `PK_Pozycjazamowienia` PRIMARY KEY (`PozycjazamowieniaID` ASC)
)

;

CREATE TABLE `Sprzataniegrobu`
(
	`Rodzajsprzatania` INT NULL,
	`SprzataniegrobuID` INT NOT NULL,
	CONSTRAINT `PK_Sprzataniegrobu` PRIMARY KEY (`SprzataniegrobuID` ASC)
)

;

CREATE TABLE `Usluga`
(
	`Koszt` DOUBLE(10,2) NULL,
	`Status` INT NULL,
	`Uwagi` VARCHAR(50) NULL,
	`UslugaID` INT NOT NULL,
	CONSTRAINT `PK_Usluga` PRIMARY KEY (`UslugaID` ASC)
)

;

CREATE TABLE `UslugaPozycjaZamowienia`
(
	`PozycjazamowieniaID` INT NULL,
	`UslugaID` INT NULL
)

;

CREATE TABLE `Uzytkownik`
(
	`Administrator` BOOL NULL,
	`Haslo` VARCHAR(50) NULL,
	`Login` VARCHAR(50) NULL,
	`Mail` VARCHAR(50) NULL,
	`Pracownik` BOOL NULL,
	`UzytkownikID` INT NOT NULL,
	CONSTRAINT `PK_Uzytkownik` PRIMARY KEY (`UzytkownikID` ASC)
)

;

CREATE TABLE `Zamowienie`
(
	`Datarealizacji` DATE NULL,
	`Datawplaty` DATE NULL,
	`ZamowienieID` INT NOT NULL,
	`UzytkownikID` INT NULL,
	CONSTRAINT `PK_Zamowienie` PRIMARY KEY (`ZamowienieID` ASC)
)

;

CREATE TABLE `Zapalenieznicza`
(
	`Modelznicza` INT NULL,
	`Rodzajwkladu` INT NULL,
	`ZapaleniezniczaID` INT NOT NULL,
	CONSTRAINT `PK_Zapalenieznicza` PRIMARY KEY (`ZapaleniezniczaID` ASC)
)

;

CREATE TABLE `Zarzadcagrobu`
(
	`Datarozpoczecia` DATE NULL,
	`Datazakonczenia` DATE NULL,
	`ZarzadcagrobuID` INT NOT NULL,
	`GrobID` INT NOT NULL,
	`OsobauprawnionaID` INT NULL,
	CONSTRAINT `PK_Zarzadcagrobu` PRIMARY KEY (`ZarzadcagrobuID` ASC)
)

;

CREATE TABLE `Zastrzezenia`
(
	`Datawniesienia` DATE NULL,
	`Opis` VARCHAR(50) NULL,
	`Wplata` DOUBLE(10,2) NULL,
	`ZastrzezeniaID` INT NOT NULL,
	`GrobID` INT NULL,
	CONSTRAINT `PK_Zastrzezenia` PRIMARY KEY (`ZastrzezeniaID` ASC)
)

;

/* Create Foreign Key Constraints */

ALTER TABLE `Akt` 
 ADD CONSTRAINT `FK_Akt_Osobazmarla`
	FOREIGN KEY (`OsobazmarlaID`) REFERENCES `Osobazmarla` (`OsobazmarlaID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Opiekungrobu` 
 ADD CONSTRAINT `FK_Opiekungrobu_Grob`
	FOREIGN KEY (`GrobID`) REFERENCES `Grob` (`GrobID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Opiekungrobu` 
 ADD CONSTRAINT `FK_Opiekungrobu_Uzytkownik`
	FOREIGN KEY (`UzytkownikID`) REFERENCES `Uzytkownik` (`UzytkownikID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Oplaceniemiejsca` 
 ADD CONSTRAINT `FK_OplacenieMiejsca_Usluga`
	FOREIGN KEY (`OplaceniemiejscaID`) REFERENCES `Usluga` (`UslugaID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Osobazmarla` 
 ADD CONSTRAINT `FK_Osobazmarla_Grob`
	FOREIGN KEY (`GrobID`) REFERENCES `Grob` (`GrobID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Pozycjazamowienia` 
 ADD CONSTRAINT `FK_Pozycjazamowienia_Grob`
	FOREIGN KEY (`GrobID`) REFERENCES `Grob` (`GrobID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Pozycjazamowienia` 
 ADD CONSTRAINT `FK_Pozycjazamowienia_Zamowienie`
	FOREIGN KEY (`ZamowienieID`) REFERENCES `Zamowienie` (`ZamowienieID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Sprzataniegrobu` 
 ADD CONSTRAINT `FK_SprzatanieGrobu_Usluga`
	FOREIGN KEY (`SprzataniegrobuID`) REFERENCES `Usluga` (`UslugaID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `UslugaPozycjaZamowienia` 
 ADD CONSTRAINT `FK_UslugaPozycjaZamowienia_PozycjaZamowienia`
	FOREIGN KEY (`PozycjazamowieniaID`) REFERENCES `Pozycjazamowienia` (`PozycjazamowieniaID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `UslugaPozycjaZamowienia` 
 ADD CONSTRAINT `FK_UslugaPozycjaZamowienia_Usluga`
	FOREIGN KEY (`UslugaID`) REFERENCES `Usluga` (`UslugaID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Zamowienie` 
 ADD CONSTRAINT `FK_Zamowienie_Uzytkownik`
	FOREIGN KEY (`UzytkownikID`) REFERENCES `Uzytkownik` (`UzytkownikID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Zapalenieznicza` 
 ADD CONSTRAINT `FK_ZapalenieZnicza_Usluga`
	FOREIGN KEY (`ZapaleniezniczaID`) REFERENCES `Usluga` (`UslugaID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Zarzadcagrobu` 
 ADD CONSTRAINT `FK_Zarzadcagrobu_Grob`
	FOREIGN KEY (`GrobID`) REFERENCES `Grob` (`GrobID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Zarzadcagrobu` 
 ADD CONSTRAINT `FK_Zarzadcagrobu_Osobauprawniona`
	FOREIGN KEY (`OsobauprawnionaID`) REFERENCES `Osobauprawniona` (`OsobauprawnionaID`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Zastrzezenia` 
 ADD CONSTRAINT `FK_Zastrzezenia_Grob`
	FOREIGN KEY (`GrobID`) REFERENCES `Grob` (`GrobID`) ON DELETE No Action ON UPDATE No Action
;

SET FOREIGN_KEY_CHECKS=1
; 
